#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

SCRIPT="/root/scunet_login.sh"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$SCRIPT"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
